apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.srvName }} 
  labels:
    release: {{ .Release.Name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.srvName }} 
  http:
  - route:
    - destination:
        host: {{ .Values.srvName }} 
        subset: release
      weight: {{ .Values.releaseWeight }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.srvName }} 
  labels:
    release: {{ .Release.Name }}
spec:
  host: {{ .Values.srvName }} 
  subsets:
  - name: release
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.srvName }} 
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
