---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
  name: {{ .Values.srvName }}-service-account
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.srvName }}-job
  labels:
    app: {{ .Values.srvName }}
spec:
  schedule: {{ .Values.schedule }}
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  selector:
    matchLabels:
      app: {{ .Values.srvName }}
  jobTemplate:
    metadata:
      labels:
        app: {{ .Values.srvName }}
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.srvName }}
            image: {{ .Values.dockerImage }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.srvName }}-secret
                  key: vault_addr
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.srvName }}-secret
                  key: vault_token
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.srvName }}-configmap
                  key: environment
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.srvName }}-configmap
                  key: domain
            - name: SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.srvName }}-configmap
                  key: service
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.srvName }}-service-account