apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.domain }}-{{ .Values.srvName }}-configmap
data:
  environment: {{ .Values.environment }}
  domain: {{ .Values.domain }}
  service: {{ .Values.srvName }}