apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.domain }}-{{ .Values.srvName }}
  labels:
    release: {{ .Values.domain }}-{{ .Values.srvName }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.domain }}-{{ .Values.srvName }}
  http:
  - route:
    - destination:
        host: {{ .Values.domain }}-{{ .Values.srvName }}
        subset: release
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.domain }}-{{ .Values.srvName }}
  labels:
    release: {{ .Values.domain }}-{{ .Values.srvName }}
spec:
  host: {{ .Values.domain }}-{{ .Values.srvName }}
  subsets:
  - name: release
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.domain }}-{{ .Values.srvName }}
  labels:
    release: {{ .Values.domain }}-{{ .Values.srvName }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: cacerts
    hosts:
    - "*"
