apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.srvName }}-vs
  labels:
    release: {{ .Values.srvName }}-vs
spec:
  hosts:
    - "{{ .Values.domain}}/{{ .Values.srvName }}"
  gateways:
    - {{ .Values.srvName }}-gw
  http:
  - route:
    - destination:
        host: {{ .Values.srvName }}-dr
        subset: release
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.srvName }}-dr
  labels:
    release: {{ .Values.srvName }}-dr
spec:
  host: {{ .Values.srvName }}-dr
  subsets:
  - name: release
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.srvName }}-gw
  labels:
    release: {{ .Values.srvName }}-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: cacerts
    hosts:
    - "{{ .Values.domain}}/{{ .Values.srvName }}"
