apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.srvName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.srvName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.httpPort }}
