name: CI workflow

on:
  workflow_call:
    secrets:
      VAULT_TOKEN:
        required: true
      VAULT_ADDRESS:
        required: true
      DOMAIN_NAME:
        required: true

jobs:
  build-test:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDRESS }}
          token: ${{ secrets.VAULT_TOKEN }}
          # Temporary skip tls verification for testing purposes
          path: secrets
          tlsSkipVerify: true
          secrets: |
            secrets/cicd/GITHUBACTION_USERNAME value | GITHUBACTION_USERNAME ;
            secrets/cicd/GITHUBACTION_TOKEN value | GITHUBACTION_TOKEN ;

      - name: Configure git for private modules
        env:
          TOKEN: ${{ env.GITHUBACTION_TOKEN }}
          GOPRIVATE: github.com/${{ secrets.DOMAIN_NAME }}
        run: git config --global url."https://${{ env.GITHUBACTION_USERNAME }}:${{ env.GITHUBACTION_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.17.0

      - name: Build
        run: go build -v ./...

      - name: Run Gosec Security Scanner
        run: gosec ./...

      - name: Test
        run: go test -v ./...
